import { Inter, Jost } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"], weight: ["100", "200", "300", "400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${jost.className}`}>
        <main className="">
          <Navbar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
